# Site Settings
title:                  "Bob Orchard"
email:                  "mail@boborchard.com"
description:            "I focus on #ux and #design to solve problems before they happen. English is my first language, but speaking User is my second. Product Design at @chargify."
baseurl:                "http://boborchard.com"
url:                    "http://boborchard.com"
logourl:                "/assets/img/bloglogo.png"
fa-logo:                "fa-bookmark-o"
paginate:               5


# Author Settings
author_name:            "Bob Orchard"
author_url:             "http://boborchard.com"
author_bio:             "I focus on #ux and #design to solve problems before they happen. English is my first language, but speaking User is my second. Product Design at @chargify."
author_email:           "mail@boborchard.com"
author_image:           "/assets/img/authorimage.jpg"


# Social Settings
twitter_url:            "http://twitter.com/boborchard"
facebook_url:           "http://facebook.com/boborchard"
github_url:             "http://github.com/boborchard"
instagram_url:          "http://instagram.com/boborchard"
linkedin_url:           "http://linkedin.com/in/boborchard"
youtube_url:            ""
dribbble_url:           ""
googleplus_url:         ""
pinterest_url:          ""


# Theme Settings
theme_disqus_shortname:   "boborchard"
theme_google_comments:    false
theme_analytics_id:       "UA-32999775-1"
theme_analytics_domain:   "boborchard.com"
theme_reading_time:       true
theme_autoload_comments:  false
theme_always_show_nav:    false


# SASS Settings
# DO NOT MODIFY
sass:
 sass_dir: "assets/css/"
 style: :compressed


# Build Settings
markdown:           kramdown
permalink:          pretty

