# Site Settings
title:                  "Bob Orchard"
email:                  "me@boborchard.com"
description:            "President of @tinypint and UI/UX Designer | Avid cyclist, geek, fan of beautiful hardware and I make made-to-order leather wallets @grwalletco"
baseurl:                "http://boborchard.com"
url:                    "http://boborchard.com"
logourl:                "/assets/img/bloglogo.png"
fa-logo:                "fa-bookmark-o"
paginate:               5


# Author Settings
author_name:            "Bob Orchard"
author_url:             "http://boborchard.com"
author_bio:             "President of @tinypint and UI/UX Designer | Avid cyclist, geek, fan of beautiful hardware and I make made-to-order leather wallets @grwalletco"
author_email:           "me@boborchard.com"
author_image:           "/assets/img/authorimage.jpg"


# Social Settings
twitter_url:            "http://twitter.com/boborchard"
facebook_url:           "http://facebook.com/boborchard"
github_url:             "http://github.com/boborchard"
instagram_url:          "http://instagram.com/boborchard"
linkedin_url:           "http://linkedin.com/in/boborchard"
youtube_url:            ""
dribbble_url:           ""
googleplus_url:         ""
pinterest_url:          ""


# Theme Settings
theme_disqus_shortname:   "ecko"
theme_google_comments:    false
theme_analytics_id:       "UA-28282324-1"
theme_analytics_domain:   "boborchard.com"
theme_reading_time:       true
theme_autoload_comments:  false
theme_always_show_nav:    false


# SASS Settings
# DO NOT MODIFY
sass:
 sass_dir: "assets/css/"
 style: :compressed


# Build Settings
markdown:           kramdown
permalink:          pretty

